server:
  port: 8765
spring:
  main:
      allow-bean-definition-overriding: true
  application:
    name: consumer-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
