server:
  port: 8763
spring:
  application:
    name: provider-hello
  datasource:
        url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8
        username: mr_zry
        password: 123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        druid:
          test-on-borrow: true
          validation-query: SELECT 1
  data:
    solr:
      host: http://localhost:8088/solr
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

mybatis:
  mapperlocations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.mr.shop
  configuration:
    map-underscore-to-camel-case: true



pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:



