server:
  port: 8763
spring:
  application:
    name: provider-hello
  datasource:
        url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: xueheng1809
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

mybatis:
 mapperlocations: classpath:mapper/*Mapper.xml
